# Docs: https://taskfile.dev/#/usage
version: "3"

tasks:
  lint:
    cmds:
      - golangci-lint run

  format:
    cmds:
      - go fmt ./...
      - go tool github.com/segmentio/golines -w .

  test:
    cmds:
      - |
        go clean -testcache
        go test ./...

  run:services:
    cmds:
      - docker compose up -d
